# Generated by Django 2.0.8 on 2018-09-14 16:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygons',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='polygons',
            name='long',
        ),
        migrations.AddField(
            model_name='polygons',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PolygonField(default='polygon()', srid=4326),
            preserve_default=False,
        ),
    ]
